on: push
name: ğŸš€ ftp website on push
jobs:
  web-deploy:
    name: ğŸ‰ ftp
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.violaonlinestore.com
        username: violaon
        password: ${{ secrets.ftp_password }}
